# 아래 내용으로 config.yml 파일을 생성한 후, python3 -m mqtt_io config.yml 명령어로 mqtt_io 모듈 실행
mqtt:
  host: mqtt.hostname.com
  port: 1883
  user: mqtt
  password: mqttpassword
  topic_prefix: gpio
  ha_discovery:
   enabled: yes 

# GPIO
gpio_modules:
  # 오렌지파이의 GPIO포트를 활용
  - name: pi_gpio 
    module: orangepi # 오렌지파이를 사용하므로, 모듈을 orangepi로 설정. 정확한 모듈을 설정하지 않으면 핀번호가 달라 오동작하게됨
    board: zero
    mode: board

digital_inputs:
  - name: gpio_door_sensor
    module: pi_gpio
    pin: 7 
    pulldown: True
    # 도어 센서일 경우 inverted옵션 True로 설정
    inverted: True
    ha_discovery:
      name: gpio_door_sensor
      device_class: door

digital_outputs:
  - name: gpio_switch
    module: pi_gpio
    pin: 12
    ha_discovery:
      name: gpio_switch
      device_class: switch
