# configuration.yaml add this
# **주의** .py 파일은 ha가 설치된 경로에 존재하여야 인식함.
# 아래의 예시는 /usr/share/hassio/homeassistant/ 경로에 zigbee_ras.py 파일을 넣어서 실행시키는 예시
shell_command:
  insert_ras: 'python3 "/config/zigbee_ras.py" "{{ temperature }}" "{{ humidity }}" "{{ pressure }}"'
  insert_db: 'python3 "/config/zigbee_db.py" "{{ temperature }}" "{{ humidity }}" "{{ pressure }}"'

# in service call automation example
alias: 라즈베리파이로 센서데이터 전송(온도)
description: ''
trigger:
  - platform: state
    entity_id: sensor.env_temperature
    attribute: state_class
condition: []
action:
  #configuration.yaml에 선언한 shell_command를 서비스호출
  - service: shell_command.insert_ras
    #data_template의 변수에 센서데이터를 넘겨서 python code를 처리할 수 있음.
    data_template:
      temperature: |
        {{ state_attr('sensor.env_temperature', 'temperature') }}
      humidity: |
        {{ state_attr('sensor.env_temperature', 'humidity') }}
      pressure: |
        {{ state_attr('sensor.env_temperature', 'pressure') }}
mode: single

#***주의*** home assistant는 docker 컨테이너 기반으로 되어 있기에, 기본적인 python만 깔려있음.
#따라서 pymysql 등의 함수를 이용하기 위해서는  docker exec -it 3bdf45abdd77 /bin/bash 와 같이 컨테이너로 직접접근하여 pip3 install pymysql 형태로 설치해주어야함.
#이는 scp시의 ssh-key도 마찬가지임
