# 기존 backend-selected 테마와 같이, 일출과 일몰에 따른 테마를 자동으로 설정하는 기능
# 2021.04.12. ceo@tabspace.kr
blueprint:
  name: (TSA-013)일출 일몰에 따른 테마 자동 변경
  description: 일출 시에 밝은 테마로, 일몰 시에 어두운 테마로 자동으로 변경됩니다. configuration.yaml에 theme설정이 사전요구됩니다.
  domain: automation
  input:
    light_theme:
      name: Google Light Theme
      description: 일몰-일출 전환시에 사용할 밝은 테마를 입력해주세요.
    dark_theme:
      name: Google Dark Theme
      description: 일출-일몰 전환시에 사용할 어두운 테마를 입력해주세요.

mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: sun.sun

action:
- choose:
  - conditions:
    - condition: state
      entity_id: sun.sun
      state: "above_horizon"
    sequence:
    - service: frontend.set_theme
      data:
        name: !input light_theme
  - conditions:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    sequence:
    - service: frontend.set_theme
      data:
        name: !input dark_theme
