blueprint:
  name: (TSA-003)SSL 인증서 만료알림
  description: 'This automation blueprint notifies when a SSL certificate is about to expire'
  domain: automation
  input:
    certificate_input:
      name: Certificate
      description: The certificate timestamp
      selector:
        entity:
          integration: cert_expiry
    days_input:
      name: Days before
      description: Set how many days before expiration it should start sending notifications
      default: 5
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: days
          mode: slider
          step: 1
    time_input:
      name: Time
      description: What time of the day it should check and send the notification?
      default: '15:00'
      selector:
        time:
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications
      selector:
        device:
          integration: mobile_app
    device_message:
      name: Message
      description: Select the message to send to the app. You can use {{expire_days_var}} for the remaining days.
      default: "SSL cert is due to expire in {{ expire_days_var }} days"
      selector:
        text:
trigger:
  platform: time
  at: !input 'time_input'
variables:
  notify_device: !input 'notify_device'
  days_var: !input 'days_input'
  certificate_var: !input 'certificate_input'
  expire_days_var: '{{ ((as_timestamp(states(certificate_var)) - as_timestamp(now())) / 60 / 60 / 24 ) | int }}'
condition:
  condition: template
  value_template: "{{ expire_days_var < days_var }}"
action:
- device_id: !input 'notify_device'
  domain: mobile_app
  type: notify
  title: 'SSL Certificate Expiration'
  message: !input 'device_message'
- event: ssl_certifcate_expiration
  event_data:
    entity: !input 'certificate_input'
    daysleft: '{{ expire_days_var }}'
