# 모션 센서의 동작감지가 발생한다면, 조명을 자동으로 켜는 블루프린트
# Zigbee2mqtt에서 entity가 switch로 인식되지 않는 경우, light로 변경 필요
# 2021.04.14. ceo@tabspace.kr
blueprint:
  name: 모션 센서 조명 켜기 (스위치 버전)
  description: 모션 센서에서 동작이 감지될 때, 선택한 조명을 자동으로 켭니다.
  domain: automation
  input:
    motion_entity:
      name: 모션 센서
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    switch_target:
      name: 조명
      selector:
        target:
          entity:
            domain: switch
    no_motion_wait:
      name: 대기 시간
      description: 모션 감지로 조명이 켜진 이후, 몇 초 뒤에 조명을 끌까요?
      default: 120
      selector:
        number:
          min: 0.0
          max: 3600.0
          unit_of_measurement: 초
          mode: slider
          step: 1.0
mode: restart
max_exceeded: silent
trigger:
  platform: state
  entity_id: !input 'motion_entity'
  from: 'off'
  to: 'on'
action:
- service: switch.turn_on
  target: !input 'switch_target'
- wait_for_trigger:
    platform: state
    entity_id: !input 'motion_entity'
    from: 'on'
    to: 'off'
- delay: !input 'no_motion_wait'
- service: switch.turn_off
  target: !input 'switch_target'
