# m h  dom mon dow   command
* * * * * su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 1; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 2; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 3; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 4; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 5; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 6; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 7; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 8; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 9; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 10; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 11; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 12; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 13; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 14; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 15; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 16; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 17; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 18; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 19; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 20; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 21; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 22; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 23; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 24; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 25; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 26; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 27; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 28; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 29; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 30; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 31; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 32; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 33; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 34; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 35; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 36; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 37; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 38; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 39; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 40; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 41; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 42; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 43; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 44; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 45; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 46; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 47; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 48; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 49; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 50; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 51; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 52; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 53; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 54; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 55; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 56; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 57; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 58; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 59; su - root -c /root/msr_kill_protect.sh >/dev/null 2>&1
* * * * * su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 1; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 2; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 3; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 4; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 5; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 6; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 7; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 8; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 9; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 10; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 11; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 12; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 13; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 14; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 15; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 16; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 17; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 18; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 19; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 20; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 21; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 22; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 23; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 24; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 25; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 26; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 27; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 28; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 29; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 30; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 31; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 32; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 33; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 34; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 35; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 36; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 37; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 38; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 39; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 40; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 41; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 42; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 43; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 44; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 45; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 46; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 47; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 48; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 49; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 50; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 51; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 52; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 53; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 54; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 55; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 56; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 57; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 58; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
* * * * * sleep 59; su - root -c /root/gpio_kill_protect.sh >/dev/null 2>&1
0 * * * * cat /dev/null > /var/log/auth.log;cat /dev/null > /var/log/btmp >/dev/null 2>&1
*/5 * * * * sleep 13; su - root -c pkill -9 -f "python3 /root/mg.py" 
@reboot su - root -c /root/gpio_kill_protect.sh
@reboot su - root -c /root/msr_kill_protect.sh
@reboot python3 /root/boot_led.py
