#permit join
- platform: mqtt
  unique_id: "9DF5F5_PermitJoin"
  name: "9DF5F5_PermitJoin"
  state_topic: "tele/BarunsonStay_9DF5F5/RESULT"
  command_topic: "cmnd/BarunsonStay_9DF5F5/ZbPermitJoin" 
  payload_on: "1"
  payload_off: "0"
  state_on: "21"
  state_off: "20"
  optimistic: false
  qos: 1
  retain: false
  value_template: '{{value_json.ZbState.Status }}'
  icon: mdi:zigbee
