- platform: mqtt
  name: "CARD001_Left" 
  state_topic: "cmnd/CARD001/POWER2" 
  payload_on: "ON" 
  payload_off: "OFF" 
  device_class: door
- platform: mqtt
  name: "CARD001_Right" 
  state_topic: "cmnd/CARD001/POWER3" 
  payload_on: "ON" 
  payload_off: "OFF" 
  device_class: door
