# Let's Encrypt Add-On의 경우, 인증서 유효기간이 발행일로부터 90일이므로, 해당 애드온의 시작(start)시에 갱신되지 않으면 
# ① 별도로 HA재기동(Let's Encrypt Add-On에서 start on boot옵션을 활성화한경우에만 해당)되거나
# ② 애드온을 다시 시작(start) 하지 않으면 갱신되지 않는 이슈가 발생
# 본 자동화는 매일 자정(12:00)에 Let's Encrypt 서비스를 재시작(항상 중지상태로 되어 있을것이므로, 결국 시작처리)하여
# 안정적인 SSL 인증서 갱신이 가능하도록 지원함
# 2021.05.17. ceo@tabspace.kr

alias: SSL 인증서 자동갱신 (SSL RENEW)
description: 'Let's Encrypt Add-On이 설치 및 세팅되어 있어야 합니다.'
trigger:
  - platform: time
    at: '00:00' # 기존 '00:00:00' 에서 HA패치관계로 변경
condition: []
action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt
mode: single
