# 내부 네트워크 핑테스트용 바이너리 센서
binary_sensor:
  - platform: ping
    host: 192.168.0.3
    name: TabSpace-301
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.0.4
    name: TabSpace-302
    count: 2
    scan_interval: 30
  - platform: ping
    host: 192.168.0.5
    name: RM4-32-c2-31
    count: 2
    scan_interval: 30
