# 외부온도 확인용
sensor:
  - platform: template
    sensors:
      weather_temperature:
        friendly_name : "GG_WEATHER"
        unit_of_measurement: 'C'
        value_template: "{{ state_attr('weather.tabspace', 'temperature') }}"
      weather_humidity:
        friendly_name : "GG_HUMIDITY"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('weather.tabspace', 'humidity') }}"

# IR리모콘 사용을 손쉽게 할 수 있는 smartir 커스텀 컴포넌트 호출 ( https://github.com/smartHomeHub/SmartIR )  
smartir:

climate:
- platform: smartir
  name: GG_AC
  unique_id: GG_AC
  # 디바이스 코드는 https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#available-codes-for-climate-devices 에서 확인
  device_code: 1062
  controller_data: remote.gg_ir_remote
  temperature_sensor: sensor.weather_temperature
  #humidity_sensor: sensor.301_temperature_humidity


media_player:
  - platform: smartir
    name: GG_TV
    unique_id: GG_TV
    # 디바이스 코드는 https://github.com/smartHomeHub/SmartIR/blob/master/docs/MEDIA_PLAYER.md 에서 확인
    device_code: 1062
    controller_data: remote.gg_ir_remote
    power_sensor: switch.gg_plug_energy
    
input_number:
  gg_tv_volume:
    icon: mdi:volume-medium
    name: Volume
    initial: 30
    min: 1
    max: 100
    step: 1
