
# HomeAssistant의 Configuration.yaml에 아래가 선언되어 있다고 가정함

# smartir:
# climate: !include climate.yaml

# smartir은 custom component로 broadlink ir remote custom component 호출을 위함
# https://github.com/smartHomeHub/SmartIR 참고

# 2021.04.15. ceo@tabspace.kr

- platform: smartir
  name: 301_ac
  unique_id: 301_ac
  # 디바이스 코드는 https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#available-codes-for-climate-devices 에서 확인
  device_code: 1062
  controller_data: remote.301_remote
  temperature_sensor: sensor.301_temperature_temperature
  humidity_sensor: sensor.301_temperature_humidity
