# 아래 코드를 사용하기 위해서는 OPENWEATHERMAP의 API발행 후, HA Integration에서 openweathermap을 추가해주어야 함.
# configuration.yaml에 template sensor 추가 필요

sensor:
  - platform: template
    sensors:
      weather_temperature:
        friendly_name : "GG_TEMPERATURE"
        unit_of_measurement: 'C'
        value_template: "{{ state_attr('weather.openweathermap', 'temperature') }}"
      weather_humidity:
        friendly_name : "GG_HUMIDITY"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('weather.openweathermap', 'humidity') }}"
        
      weather_pressure:
        friendly_name : "GG_PRESSURE"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('weather.openweathermap', 'pressure') }}"

      weather_wind_bearing:
        friendly_name : "GG_WIND_BEARING"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('weather.openweathermap', 'wind_bearing') }}"

      weather_wind_speed:
        friendly_name : "GG_WIND_SPEED"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('weather.openweathermap', 'wind_speed') }}"
